/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal.pascal.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.pascal.pascal.PascalPackage;
import org.xtext.example.pascal.pascal.abstraction_declaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>abstraction declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class abstraction_declarationImpl extends MinimalEObjectImpl.Container implements abstraction_declaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected abstraction_declarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.ABSTRACTION_DECLARATION;
  }

} //abstraction_declarationImpl
