/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PascalStandaloneSetup /* implements PascalStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type PascalStandaloneSetup");
  }
}
