/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>abstraction declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getabstraction_declaration()
 * @model
 * @generated
 */
public interface abstraction_declaration extends EObject
{
} // abstraction_declaration
