/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>strutured type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pascal.pascal.strutured_type#isPacked <em>Packed</em>}</li>
 *   <li>{@link org.xtext.example.pascal.pascal.strutured_type#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.pascal.pascal.PascalPackage#getstrutured_type()
 * @model
 * @generated
 */
public interface strutured_type extends EObject
{
  /**
   * Returns the value of the '<em><b>Packed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Packed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packed</em>' attribute.
   * @see #setPacked(boolean)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getstrutured_type_Packed()
   * @model
   * @generated
   */
  boolean isPacked();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.strutured_type#isPacked <em>Packed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Packed</em>' attribute.
   * @see #isPacked()
   * @generated
   */
  void setPacked(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(unpacked_strutured_type)
   * @see org.xtext.example.pascal.pascal.PascalPackage#getstrutured_type_Type()
   * @model containment="true"
   * @generated
   */
  unpacked_strutured_type getType();

  /**
   * Sets the value of the '{@link org.xtext.example.pascal.pascal.strutured_type#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(unpacked_strutured_type value);

} // strutured_type
