package org.xtext.example.pascal.validation;

public enum ErrorType {

	REDECLARATION, NOT_DECLARATION, CONSTANT_ASSIGNMENT, CONSTANT_ONLY, 
	FUNCTION_ONLY, TYPE_CONVERSION_ERROR, UNDEFINED_TYPE, INVALID_OPERATOR, 
	NOT_INITIALIZED, TYPE_COHESION
	
}